language: node_js
node_js:
  - "10"
script:
  - npm build
deploy:
  provider: lambda
  function_name: "ka-hua-olelo-o-ka-la"
  region: "us-west-2"
  role: $AWS_ROLE
  runtime: "nodejs10.x"
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
